name: Terraform AWS Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
  TF_VERSION: 1.15.5

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Step 1 - Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Step 2 - Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Display configured AWS region
      run: aws sts get-caller-identity

    - name: Step 4 - Terraform Init 
      run: terraform init --upgrade

    - name: Step 5 - Terraform Plan
      run: terraform plan -var-file="dev.tfvars"

    - name: Step 6 - Terraform Apply
      run: terraform apply -var-file="dev.tfvars" -auto-approve